apiVersion: v1
kind: Pod
metadata:
  name: microk8s-backup
spec:
  restartPolicy: OnFailure
  securityContext:
    runAsUser: 0
    runAsGroup: 998
    fsGroup: 1000
  volumes:
    - name: kine
      hostPath:
        path: /var/snap/microk8s/current/var/kubernetes/backend/kine.sock
        type: Socket
  containers:
    - name: dbctl
      image: clowa/microk8s-backup
      imagePullPolicy: Always
      env:
        - name: AWS_REGION
          value: eu-central-1
        - name: AWS_ACCESS_KEY_ID
          value: XXXXXXXXXXXXXXXXXXXX # CHANGE ME
        - name: AWS_SECRET_ACCESS_KEY
          value: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX # CHANGE ME
        - name: BUCKET
          value: my-s3-bucket # CHANGE ME
        - name: KEY
          value: backup/microk8s/
        - name: KINE_ENDPOINT
          value: "/kine.sock"
      volumeMounts:
        - name: kine
          mountPath: /kine.sock
      securityContext:
        allowPrivilegeEscalation: false
      resources:
        requests:
          cpu: "20m"
          memory: "20Mi"
        limits:
          cpu: "100m"
          memory: "64Mi"
